[package]
name = "lapce-ui"
version = "0.2.4"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]
edition = "2021"

[dependencies]
base64 = "0.13.0"
clap = { version = "3.2.17", features = ["derive"] }
image = "0.24.3"
chrono = "0.4.19"
log = "0.4.14"
fern = "0.6.0"
Inflector = "0.11.4"
rayon = "1.5.1"
alacritty_terminal = "0.17.0"
itertools = "0.10.1"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
unicode-width = "0.1.8"
im = { version = "15.0.0", features = ["serde"] }
regex = "1.5.6"
include_dir = "0.6.0"
anyhow = "1.0.32"
once_cell = "1.15"
serde = "1.0"
serde_json = "1.0"
lapce-xi-rope = { version = "0.3.1", features = ["serde"] }
lsp-types = { version = "0.93", features = ["proposed"] }
toml_edit = { version = "0.14.4", features = ["easy"] }
open = "3.0.2"

# lapce deps
druid = { git = "https://github.com/lapce/druid", branch = "shell_opengl", features = ["svg", "im", "serde"] }
# druid = { path = "../../druid/druid", features = ["svg", "im" , "serde"] }
lapce-data = { path = "../lapce-data" }
lapce-rpc = { path = "../lapce-rpc" }
lapce-core = { path = "../lapce-core" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[features]
default = ["compile-languages", "lapce-data/updater"]
portable = ["lapce-data/portable"]
compile-languages = ["lapce-core/compile-grammars"]
