[package]
name = "lapce-core"
version = "0.2.4"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]
edition = "2021"

[dependencies]
libloading = "0.7"
directories = "4.0"
thiserror = "1.0"
itertools = "0.10.3"
log = "0.4.14"
bitflags = "1.3.2"
once_cell = "1.15"
slotmap = "1.0"
arc-swap = "1.5.1"
strum = "0.24.0"
strum_macros = "0.24"
serde = "1.0"
lsp-types = { version = "0.93", features = ["proposed"] }
lapce-xi-rope = { version = "0.3.1", features = ["serde"] }
lapce-rpc = { path = "../lapce-rpc" }

# mod config
druid = { git = "https://github.com/lapce/druid", branch = "shell_opengl", features = [ "svg", "im", "serde", ] }
indexmap = "1.9"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
structdesc = { git = "https://github.com/lapce/structdesc" }
toml_edit = { version = "0.15", features = ["easy"] }
anyhow = "1.0"
include_dir = "0.7"
config = { version = "0.13", default-features = false, features = ["toml"] }
serde_json = "1.0"
chrono = "0.4"

tree-sitter = "0.20.7"

# plaintext grammar, not optional
tree-sitter-plaintext = { git = "https://github.com/panekj/tree-sitter-plaintext", rev = "38c37a098fea0eec26c6b0aeaa9feaec8bbe93fe" }
# please keep below dependencies and features sorted just like LANGUAGES in language.rs

tree-sitter-bash = { git = "https://github.com/tree-sitter/tree-sitter-bash", branch = "master", optional = true }
tree-sitter-c = { version = "0.20.2", optional = true }
tree-sitter-c-sharp = { git = "https://github.com/tree-sitter/tree-sitter-c-sharp", branch = "master", optional = true }
tree-sitter-cpp = { version = "0.20.0", optional = true }
tree-sitter-cmake = { version = "0.1.0", optional = true }
# switch to upstream version after this is merged https://github.com/tree-sitter/tree-sitter-css/pull/22
tree-sitter-css = { git = "https://github.com/syntacti/tree-sitter-css", branch = "master", optional = true }
tree-sitter-d = {  git = "https://github.com/ghishadow/tree-sitter-d", branch = "main", optional = true }
tree-sitter-dart = { git = "https://github.com/syntacti/tree-sitter-dart", branch = "master", optional = true }
tree-sitter-dockerfile = { git = "https://github.com/panekj/tree-sitter-dockerfile", branch = "queries", optional = true }
tree-sitter-elixir = { git = "https://github.com/elixir-lang/tree-sitter-elixir.git", version = "0.19.0", optional = true }
tree-sitter-elm = { version = "5.6.0", optional = true }
tree-sitter-erlang = { git = "https://github.com/WhatsApp/tree-sitter-erlang", branch = "main", optional = true }
tree-sitter-glimmer = { git = "https://github.com/VixieTSQ/tree-sitter-glimmer", version = "0.0.1", optional = true }
tree-sitter-glsl = { git = "https://github.com/theHamsta/tree-sitter-glsl", branch = "add-highlights.scm", optional = true }
tree-sitter-go = { version = "0.19.1", optional = true }
tree-sitter-hare = { version = "0.20.7", optional = true }
tree-sitter-haskell = { git = "https://github.com/tree-sitter/tree-sitter-haskell", version = "0.14.0", optional = true }
tree-sitter-haxe = { git = "https://github.com/vantreeseba/tree-sitter-haxe", version = "0.2.2", optional = true }
tree-sitter-hcl = { git = "https://github.com/VixieTSQ/tree-sitter-hcl", version = "0.0.1", optional = true }
tree-sitter-html = { version = "0.19.0", optional = true }
tree-sitter-java = { git = "https://github.com/tree-sitter/tree-sitter-java.git", version = "0.20.0", optional = true }
tree-sitter-javascript = { version = "0.20.0", optional = true }
# new version cannot be published on crates.io - https://github.com/tree-sitter/tree-sitter-json/issues/21
# tree-sitter-json = { version = "0.19.0", optional = true }
tree-sitter-json = { git = "https://github.com/tree-sitter/tree-sitter-json.git", rev = "11e2cc12d9b267766fb11a06e52952792fd8e3f0", optional = true }
tree-sitter-julia = { git = "https://github.com/varlad/tree-sitter-julia", branch = "master", optional = true }
tree-sitter-kotlin = { git = "https://github.com/fwcd/tree-sitter-kotlin", branch = "main", optional = true }
tree-sitter-latex = { git = "https://github.com/latex-lsp/tree-sitter-latex", branch = "master", optional = true }
tree-sitter-lua = { git = "https://github.com/syntacti/tree-sitter-lua", branch = "main", optional = true }
tree-sitter-md = { git = "https://github.com/MDeiml/tree-sitter-markdown.git", branch = "split_parser", optional = true }
tree-sitter-nix = { git = "https://github.com/cstrahan/tree-sitter-nix", branch = "master", optional = true }
tree-sitter-ocaml = { git = "https://github.com/tree-sitter/tree-sitter-ocaml", version = "0.20.0", optional = true }
tree-sitter-php = { git = "https://github.com/tree-sitter/tree-sitter-php.git", version = "0.19.1", optional = true }
tree-sitter-prisma-io = { version = "1.3.0", optional = true }
tree-sitter-protobuf = { git = "https://github.com/yusdacra/tree-sitter-protobuf", branch = "main", optional = true }
tree-sitter-python = { version = "0.20.1", optional = true }
tree-sitter-ql = { git = "https://github.com/tree-sitter/tree-sitter-ql", version = "0.19.0", optional = true }
tree-sitter-r = { version = "0.19.5", optional = true }
tree-sitter-ruby = { git = "https://github.com/tree-sitter/tree-sitter-ruby.git", rev = "656abef", optional = true }
tree-sitter-rust = { version = "0.20.0", optional = true }
tree-sitter-scheme = { git = "https://github.com/6cdh/tree-sitter-scheme.git", branch = "main", optional = true }
tree-sitter-scss = { git = "https://github.com/VixieTSQ/tree-sitter-scss", version = "0.0.1", branch = "patch-1", optional = true }
# switch to upstream version after this is merged  https://github.com/m-novikov/tree-sitter-sql/pull/68
tree-sitter-sql = { git = "https://github.com/oknozor/tree-sitter-sql", branch = "main", optional = true }
tree-sitter-svelte = { git = "https://github.com/Himujjal/tree-sitter-svelte", branch = "master", optional = true }
tree-sitter-swift = { version = "0.3.4", optional = true }
tree-sitter-toml = { version = "0.20.0", optional = true }
tree-sitter-typescript = { version = "0.20.0", optional = true }
tree-sitter-vue = { version = "0.0.3", optional = true }
tree-sitter-wgsl = { git = "https://github.com/szebniok/tree-sitter-wgsl", branch = "master", optional = true }
tree-sitter-xml = { git = "https://github.com/RenjiSann/tree-sitter-xml", branch = "main", optional = true }
tree-sitter-yaml = { git = "https://github.com/panekj/tree-sitter-yaml", branch = "master", optional = true }
tree-sitter-zig = { git = "https://github.com/maxxnino/tree-sitter-zig", branch = "main", optional = true }

[features]
default = ["compile-grammars"]
compile-grammars = [
    "dep:tree-sitter-bash",
    "dep:tree-sitter-c",
    "dep:tree-sitter-cmake",
    "dep:tree-sitter-cpp",
    "dep:tree-sitter-c-sharp",
    "dep:tree-sitter-css",
    "dep:tree-sitter-d",
    "dep:tree-sitter-dart",
    "dep:tree-sitter-dockerfile",
    "dep:tree-sitter-elixir",
    "dep:tree-sitter-elm",
    "dep:tree-sitter-erlang",
    "dep:tree-sitter-glimmer",
    "dep:tree-sitter-glsl",
    "dep:tree-sitter-go",
    "dep:tree-sitter-hare",
    "dep:tree-sitter-haskell",
    "dep:tree-sitter-haxe",
    "dep:tree-sitter-hcl",
    "dep:tree-sitter-html",
    "dep:tree-sitter-java",
    "dep:tree-sitter-javascript",
    "dep:tree-sitter-json",
    "dep:tree-sitter-julia",
    "dep:tree-sitter-kotlin",
    "dep:tree-sitter-latex",
    "dep:tree-sitter-lua",
    "dep:tree-sitter-md",
    "dep:tree-sitter-nix",
    "dep:tree-sitter-ocaml",
    "dep:tree-sitter-php",
    "dep:tree-sitter-prisma-io",
    "dep:tree-sitter-protobuf",
    "dep:tree-sitter-python",
    "dep:tree-sitter-ql",
    "dep:tree-sitter-r",
    "dep:tree-sitter-ruby",
    "dep:tree-sitter-rust",
    "dep:tree-sitter-scheme",
    "dep:tree-sitter-scss",
    "dep:tree-sitter-sql",
    "dep:tree-sitter-svelte",
    "dep:tree-sitter-swift",
    "dep:tree-sitter-toml",
    "dep:tree-sitter-typescript",
    "dep:tree-sitter-vue",
    "dep:tree-sitter-wgsl",
    "dep:tree-sitter-yaml",
    "dep:tree-sitter-xml",
    "dep:tree-sitter-zig",
    "dep:tree-sitter-sql",
]